.\" Copyright (c) 2016, Dmitrij D. Czarkoff
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: September 19 2016$
.Dt UNUTF8 1
.Os
.Sh NAME
.Nm unutf8
.Nd convert text to Unicode codepoints
.Sh SYNOPSIS
.Nm
.Op Fl dhvx
.Op Ar string
.Sh DESCRIPTION
.Nm
decodes UTF-8-encoded text and prints Unicode codepoints, one per line.
If no arguments provided on the command line,
.Nm
reads text from standard input.
.Pp
.Nm
stops processing after first error in input.
.Pp
The following flags are available:
.Bl -tag -width indent
.It Fl d
Print codepoints in decimal notation.
Decimals are formatted as XML escape codes.
.It Fl x
Print codepoints in hexadecimal notation.
Hexadecimals are formatted according to Notation Conventions in Unicode
Standard.
This is the default.
.It Fl s
When reading text from command line arguments, delimit output with line breaks.
.It Fl v
Verbose output.
Prefix codepoints with input text.
.It Fl h
Print help message and exit.
.El
.Pp
When outputing multiple values per line (eg. in verbose mode, or when both
decimal and hexadecimal notations are requested), the fields are separated with
tab character.
.Sh AUTHOR
.An Dmitrij D. Czarkoff Aq czarkoff@gmail.com .
